[[row]]
 ratio=30
 [[row.child]]
 type="cpu"
[[row]]
   ratio=40
   [[row.child]]
     ratio=4
     type="mem"
   [[row.child]]
     ratio=3
     [[row.child.child]]
       type="temp"
     [[row.child.child]]
       type="disk"
[[row]]
 ratio=30
 [[row.child]]
   type="net"
 [[row.child]]
   type="proc"
   default=true


[flags]
rate = "500ms"
temperature_type = "c"
default_time_value = "30s"

[processes]
columns = ["Pid", "Name", "CPU%", "Mem%", "R/s", "W/s", "T.Read", "T.Write", "User", "State"]

[colors]
table_header_color="Gray"
widget_title_color="#f6ce08"

all_cpu_color="#639eea"
avg_cpu_color="#f6ce08"
cpu_core_colors=["#bfbfbf", "#b8b8b8", "#afafaf", "#a8a8a8", "#9f9f9f", "#989898", "#8f8f8f", "#888888", "#7f7f7f", "#787878"]
ram_color="#639eea"
swap_color="#f6ce08"
rx_color="#639eea"
tx_color="#f6ce08"

border_color="White"
highlighted_border_color="#639eea"

text_color="White"
selected_text_color="Black"
selected_bg_color="#fae46d"
graph_color="White"

high_battery_color="green"
medium_battery_color="yellow"
low_battery_color="red"