shell = "zsh"

[plugins.zsh-defer]
apply = ["source"]
github = "romkatv/zsh-defer"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.zsh-syntax-highlighting]
apply = ["defer"]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
apply = ["defer"]
github = "zsh-users/zsh-autosuggestions"
use = ['{{ name }}.zsh']

[plugins.zsh-completions]
apply = ['defer']
github = 'zsh-users/zsh-completions'

[plugins.zoxide]
github = 'ajeetdsouza/zoxide'

[plugins.thefuck]
inline = 'eval $(thefuck --alias fuck)'

[plugins.zsh-pyenv-lazy]
apply = ["source"]
github = "davidparsson/zsh-pyenv-lazy"

[plugins.zsh-autopair]
apply = ["defer"]
github = "hlissner/zsh-autopair"

[plugins.compinit]
inline = 'autoload -Uz compinit && compinit'

[plugins.compinit.hooks]
pre = "zstyle :compinstall filename '$HOME/.zshrc'"

[plugins.local-defer]
apply = ['defer']
local = '~/.config/zsh/defer'
use = ['*.zsh']

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"
