[theme]
theme = "ctp-mocha"

[icons]
icons = "awesome6"

[[block]]
block = "net"
format = "  $icon  {$ssid   $ip}  "
interval = 5


[[block]]
block = "sound"

[[block.click]]
button = "left"
cmd = "alsamixer"

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "time"
interval = 1

[block.format]
full = " $icon $timestamp.datetime(f:'%Y/%m/%d %H:%M:%S(%a)') "