[colors]
foreground = "#eeeeee"
background = "#000000"
cursor_bg = "#fae46d"
cursor_border = "#fae46d"
cursor_fg = "#fae46d"
selection_bg = "#403216"
selection_fg = "#ffffff"

ansi = ["#222222","#42b5eb","#ffda0f","#fad26d","#ffc56e","#ffbe6e","#5eb7f2","#cccccc"]
brights = ["#666666","#72d0fc","#ffed8a","#f0d081","#f0c481","#f7c78d","#7cc3f2","#eeeeee"]

[metadata]
name = 'xflest'
