alias wget="aria2c"
alias man="tldr"

alias ga="git add"
alias gap="git add -p"
alias gc="git commit -m"
alias gca="git commit --amend --no-edit"
alias s="git status"
alias l="git log"
alias gps="git push"
alias gpl="git pull"
alias gf="git fetch"
alias gm="git merge"
alias gmf="git merge FETCH_HEAD"
alias gr="git reset"
alias grg="git reset --hard"
alias grs="git reset --soft"
alias gd="git diff"

alias dc="docker compose"
alias dcup="dockercompose up -d"
alias dcps="docker compose ps"
alias dcrm="docker compose rm"

alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias sv="sudo nvim"

alias ls="exa --icons --git"
alias la="exa --icons --git  -a"
alias ll="exa --icons --git -aahl"
alias lt="exa -T -L 3 -a -I 'node_modules|.git|.cache' --icons"
