name: cache

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      GH_TOKEN: ${{ secrets.GH_READ_TOKEN }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Grant access to private flake inputs
        run: gh auth setup-git
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: mst-mkt
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-on-droid
          pushFilter: (-source$|bun-pkg-|\.tgz$|-pnpm-deps$|-go-modules$)
      - run: nix build --impure .#nixOnDroidConfigurations.fogcanyon.activationPackage
